/*
 * [y] hybris Platform
 *
 * Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This software is the confidential and proprietary information of SAP
 * ("Confidential Information"). You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with SAP.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.12 at 10:25:11 AM EDT
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.hybris.com/customersupportbackoffice/config/customersupportrefineby", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.hybris.platform.omsbackoffice.config.impl.jaxb.hybris.customersupportrefineby;
