/*
 * [y] hybris Platform
 *
 * Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This software is the confidential and proprietary information of SAP
 * ("Confidential Information"). You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with SAP.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.12 at 10:25:11 AM EDT
//


package de.hybris.platform.omsbackoffice.config.impl.jaxb.hybris.customersupportrefineby;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import com.hybris.cockpitng.core.config.annotations.Mergeable;


/**
 * <p>Java class for SearchValue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchValue">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="group-member-value" type="{http://www.hybris.com/customersupportbackoffice/config/customersupportrefineby}GroupMemberValue" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="uniqueValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="merge-mode" type="{http://www.hybris.com/customersupportbackoffice/config/customersupportrefineby}MergeMode" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchValue", propOrder = {
    "groupMemberValue"
})
public class SearchValue {

    @Mergeable(key = "value")
    @XmlElement(name = "group-member-value", required = true)
    protected List<GroupMemberValue> groupMemberValue;
    @XmlAttribute(name = "uniqueValue")
    protected String uniqueValue;
    @XmlAttribute(name = "label", required = true)
    protected String label;
    @XmlAttribute(name = "merge-mode")
    protected MergeMode mergeMode;

    /**
     * Gets the value of the groupMemberValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupMemberValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupMemberValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GroupMemberValue }
     * 
     * 
     */
    public List<GroupMemberValue> getGroupMemberValue() {
        if (groupMemberValue == null) {
            groupMemberValue = new ArrayList<GroupMemberValue>();
        }
        return this.groupMemberValue;
    }

    /**
     * Gets the value of the uniqueValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUniqueValue() {
        return uniqueValue;
    }

    /**
     * Sets the value of the uniqueValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUniqueValue(String value) {
        this.uniqueValue = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }

    /**
     * Gets the value of the mergeMode property.
     * 
     * @return
     *     possible object is
     *     {@link MergeMode }
     *     
     */
    public MergeMode getMergeMode() {
        return mergeMode;
    }

    /**
     * Sets the value of the mergeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link MergeMode }
     *     
     */
    public void setMergeMode(MergeMode value) {
        this.mergeMode = value;
    }

}
