/*
 * [y] hybris Platform
 *
 * Copyright (c) 2018 SAP SE or an SAP affiliate company.  All rights reserved.
 *
 * This software is the confidential and proprietary information of SAP
 * ("Confidential Information"). You shall not disclose such Confidential
 * Information and shall use it only in accordance with the terms of the
 * license agreement you entered into with SAP.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.12 at 10:37:05 AM EDT 
//


package de.hybris.platform.warehousingbackoffice.config.impl.jaxb.hybris.warehousingrefineby;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the de.hybris.platform.warehousingbackoffice.config.impl.jaxb.hybris.warehousingrefineby package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: de.hybris.platform.warehousingbackoffice.config.impl.jaxb.hybris.warehousingrefineby
     * 
     */
    public ObjectFactory() {
        // left empty intentionally
    }

    /**
     * Create an instance of {@link RefineBy }
     * 
     */
    public RefineBy createRefineBy() {
        return new RefineBy();
    }

    /**
     * Create an instance of {@link FieldList }
     * 
     */
    public FieldList createFieldList() {
        return new FieldList();
    }

    /**
     * Create an instance of {@link SearchField }
     * 
     */
    public SearchField createSearchField() {
        return new SearchField();
    }

    /**
     * Create an instance of {@link SearchValue }
     * 
     */
    public SearchValue createSearchValue() {
        return new SearchValue();
    }

    /**
     * Create an instance of {@link GroupMemberValue }
     * 
     */
    public GroupMemberValue createGroupMemberValue() {
        return new GroupMemberValue();
    }

}
